kind: Service
apiVersion: v1
metadata:
  name: rms-gateway
  namespace: rms-gateway
spec:
  type: ClusterIP
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: rms-gateway
    deployment: rms-gateway