spring:
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://172.19.216.202:5432/rms
    username: postgres
    password: snubi1004
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 0