spring:
  application:
    name: rms-lims-service
  main:
    web-application-type: reactive
  cloud:
    function:
      definition: reportSubscribe;workflowSubscribe;
    stream:
      bindings:
        reportSubscribe-in-0:
          destination: report
          group: report-subscriber-test
        workflowSubscribe-in-0:
          destination: workflow-event
          group: rms-test-subscriber-dev
      kafka:
        binder:
          brokers: 172.19.208.171, 172.19.208.172, 172.19.208.101, 172.19.208.102, 172.19.208.111
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_URL}/report_service?schema=rms_dev
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    pool:
      initial-size: 2
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1
aws:
  credentials:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
  s3:
    endpoint: ${S3_ENDPOINT}
    bucket: ${S3_BUCKET}

logging:
  level:
    io.r2dbc.postgresql.QUERY: TRACE

server:
  port: 9090