spring:
  application:
    name: alis-sync
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:postgresql://172.19.208.223:5432/rms
    username: postgres
    password: K9IhSJDIaqrQ4zgU4w2RehD3Rt1qNOkHgSTJPHKQa57sZNzwzKWjxfNElA6W4zQX
    pool:
      initial-size: 2
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1
aws:
  credentials:
    access-key: 8331SD7MTPDP6I16OJZT
    secret-key: mjZJcgLb8dvOlrkEWCoc9g4xEm7TZFd0otGmhqDM
  s3:
    endpoint: https://s3.apps.gcgenome.com
    bucket: bucket-86994bb8-28b7-4cbf-9842-4f314caae474
logging:
  level:
    io.r2dbc.postgresql.QUERY: TRACE
    io.r2dbc.postgresql.PARAM: TRACE
    root: info
  file:
    path: E:\Intellij log folder
server:
  port: 9090

