spring:
  application:
    name: rms-alis-api
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: test:12181
      discovery:
        root: /rms
  r2dbc:
    url: r2dbc:postgresql://172.19.216.212:5432/rms?schema=public
    username: postgres
    password: snubi1004
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1
logging:
  level:
    io.r2dbc.postgresql.QUERY: TRACE
    io.r2dbc.postgresql.PARAM: TRACE
greencross:
  alis:
    private:
      modulus: pLmNslOM6l7Y/GFKk/HsCp9xNDVpFd12pHiD2ZiFEK/sHfohCZeU4mvzakrwxcDFxWIbRHTpOFmgCiKpeXMUgYJQpkKVdZm7xgOwMNhSIYsK3gJ/G0+bDFBSQAK8belIuED/6B+Lwq9pWczLomIelD0WZsV1Y2k6l+RnNUoJYes=
      exponent: gw87JQoC0Sqbu9nwy1stMZqAKEjijkoBLoTQat1F6ev+ki9D/+zBwZCgQA7WGJDzCcOv7DyUnof4pHfFnWKpicYmw3fZhIimixVPUJMc+2b4rno+X3PDMF+Eakas8xTo0sMRdCOA9kFfwt4nBj11WbJldtTLkoy6C745VyzcvnE=
server:
  port: 56105
