apiVersion: v2
appVersion: v1.16.0
type: application
name: postgresql-ha
version: 11.9.2
home: https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha
icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
dependencies:
  - name: lims-postgresql-ha
    version: 0.3.0
    repository: https://gitea.apps.gcgenome.com/api/packages/LIMS/helm