lims-postgresql-ha:
  postgresql-ha:
    global:
      postgresql:
        database: rms
        existingSecret: postgresql
      pgpool:
        existingSecret: postgresql
    commonLabels:
      app.kubernetes.io/part-of: database
      app.kubernetes.io/name: postgresql
    commonAnnotations:
      app.openshift.io/vcs-uri: 'https://github.com/bitnami/charts/tree/main/bitnami/postgresql-ha'
    postgresql:
      tolerations:
        - key: database
          operator: Exists
          effect: NoSchedule
      podLabels:
        app: postgresql
        version: 15.4.0
      podAnnotations:
        sidecar.istio.io/inject: 'true'
      extendedConf: password_encryption = md5
    pgpool:
      podLabels:
        app: postgresql
        version: 4.4.4
      podAnnotations:
        sidecar.istio.io/inject: 'true'
      authenticationMethod: md5
    serviceAccount:
      create: true
      name: postgres
    persistence:
      storageClass: local
    volumePermissions:
      enabled: true
    service:
      type: LoadBalancer