kind: ConfigMap
apiVersion: v1
metadata:
  name: alis
  namespace: {{ .Release.Namespace }}
data:
  alis.yaml: |
    alis:
      private:
        modulus: ${alis.private-modulus}
        exponent: ${alis.private-exponent}
