kind: ConfigMap
apiVersion: v1
metadata:
  name: authorization
  namespace: {{ .Release.Namespace }}
data:
  authorization.yaml: |
    spring:
      security:
        oauth2:
          authorization:
            header: Authorization
            jwt:
              signature-algorithm: RS256
              duration: 36000
              secret: ${jwt.private}
