kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-s3
  namespace: {{ .Release.Namespace }}
data:
  aws-s3.yaml: |
    aws:
      credentials:
        access-key: ${rms-s3-credentials.access-key}
        secret-key: ${rms-s3-credentials.secret-key}
      s3:
        endpoint: ${rms-s3-credentials.endpoint}
        bucket: ${rms-s3-credentials.bucket}
