apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: a{{ .Values.host }}-ca
  namespace: {{ .Release.Namespace }}
spec:
  commonName: a{{ .Values.host }}
  dnsNames:
    - a{{ .Values.host }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: {{ .Values.host }}-ca