apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cert-manager-service
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
    - gateway
  hosts:
    - {{ .Values.host }}
  http:
    - match:
        - uri:
            prefix: /.well-known
      route:
        - destination:
            host: cm-acme-http-solver-4kj48.rms-test.svc.cluster.local
