apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Namespace }}-cloudnative-pg
  namespace: openshift-gitops
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: 'https://kubernetes.default.svc'
  project: {{ .Release.Namespace }}
  sources:
    - path: charts/cloudnative-pg
      repoURL: 'https://gitea.apps.gcgenome.com/LIMS/rms.git'
      targetRevision: {{ .Values.revision }}
      helm:
        parameters:
          - name: "host"
            value: {{ .Values.host }}
          {{- with .Values.postgresql.persistence.size }}
          - name: "persistence.size"
            value: {{ . | quote }}
          {{- end }}
          {{- with .Values.postgresql.persistence.storageClass }}
          - name: "persistence.storageClass"
            value: {{ . | quote }}
          {{- end }}
        values: |
          bucket: {{ .Values.bucket }}
          {{- with .Values.postgresql.tolerations }}
          tolerations: {{ toYaml .  | nindent 10 }}
          {{- end }}
  revisionHistoryLimit: 0