kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
data:
  kafka.yaml: |
    spring:
      cloud:
        function:
          definition: reportSubscribe;workflowSubscribe;
        stream:
          bindings:
            reportSubscribe-in-0:
              destination: report
              group: rms-test-subscriber
            workflowSubscribe-in-0:
              destination: workflow-event
              group: rms-test-subscriber
          kafka:
            binder:
              brokers: ${kafka.gemini}, ${kafka.pisces}, ${kafka.aries}, ${kafka.taurus}, ${kafka.libra}
