kind: ConfigMap
apiVersion: v1
metadata:
  name: labs-database
  namespace: {{ .Release.Namespace }}
data:
  labs-database.yaml: |
    spring:
      r2dbc:
        url: ${labs-database.url}
        username: ${labs-database.username}
        password: ${labs-database.password}
        pool:
          initial-size: 2
          max-size: 50
          max-idle-time: 30m
          validation-query: SELECT 1
