kind: ConfigMap
apiVersion: v1
metadata:
  name: s3
  namespace: {{ .Release.Namespace }}
data:
  s3.yaml: |
    aws:
      credentials:
        access-key: 1MI7K07L3RZF4G7XXK0J
        secret-key: xvCHemrdHb9tJj6KhHDyBKlU20piGBoiF1Ok7SED
      s3:
        endpoint: ${rms-s3-credentials.endpoint}
        bucket: ${rms-s3-credentials.bucket}
