apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh
  namespace: openshift-gitops
spec:
  destination:
    namespace: {{ .Release.Namespace }}-service-mesh
    server: 'https://kubernetes.default.svc'
  project: {{ .Release.Namespace }}
  source:
    path: charts/service-mesh
    repoURL: 'https://gitea.apps.gcgenome.com/LIMS/rms.git'
    targetRevision: {{ .Values.revision }}
    helm:
      parameters:
        - name: "host"
          value:  {{ .Values.host }}
        - name: "ip"
          value:  {{ .Values.ip }}
        - name: "network"
          value:  {{ .Values.network }}
        - name: "targetNamespace"
          value:  {{ .Release.Namespace }}