spring:
  application:
    name: rms-order
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: test:12181
      discovery:
        root: /rms
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - Authentication
              - AUTHORIZATION
              - X-USER-ID
              - Content-Type
            exposedHeaders:
              - X-Total-Count
              - X-Total-Page
              - X-Current-Page
              - X-Frame-Options
            allowedMethods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
  r2dbc:
    url: r2dbc:postgresql://libra:5432/report_service?schema=rms
    username: report_service
    password: rs1004!@
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1
logging:
  level:
    io.r2dbc.postgresql.QUERY: TRACE
#    io.r2dbc.postgresql.PARAM: TRACE
server:
  port: 9295
