package com.gcgenome.rms.exceptions

import org.springframework.security.authentication.AuthenticationCredentialsNotFoundException

class AuthenticationNotFoundException: AuthenticationCredentialsNotFoundException("인증되지 않은 사용자입니다.")