spring:
  application:
    name: rms-service
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: test:12181
      discovery:
        root: /rms
  r2dbc:
    url: r2dbc:postgresql://libra:5432/report_service?schema=rms_dev
    username: postgres
    password: snubi1004
    pool:
      initial-size: 2
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1
server:
  port: 4444

logging:
  level:
    io.r2dbc.postgresql.QUERY: TRACE # for queries