apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: {{ .Release.Namespace }}
spec:
  imageName: image-registry.openshift-image-registry.svc:5000/library/cloudnative-pg-postgres:16.0
  backup:
    {{- with .Values.bucket }}
    barmanObjectStore:
      destinationPath: 's3://{{ . }}/backup'
      endpointURL: 'https://s3.apps.gcgenome.com'
      s3Credentials:
        accessKeyId:
          key: access-key
          name: s3-credentials
        inheritFromIAMRole: false
        secretAccessKey:
          key: secret-key
          name: s3-credentials
      wal:
        compression: bzip2
        maxParallel: 8
    retentionPolicy: 3m
    target: prefer-standby
  {{- end }}
  instances: 3
  storage:
    {{- with .Values.persistence.size }}
    size: {{ . | quote }}
    {{- end }}
    {{- with .Values.persistence.storageClass }}
    storageClass: {{ . | quote }}
    {{- end }}
  {{- with .Values.tolerations }}
  affinity:
    tolerations: {{ toYaml . | nindent 4 }}
  {{- end }}
  postgresql:
    parameters:
      timezone: "Asia/Seoul"
  superuserSecret:
    name: postgresql
  bootstrap:
    initdb:
      database: rms
      owner: postgres
      encoding: UTF8
      localeCollate: UTF-8
      localeCType: UTF-8
      options:
        - '--locale-provider=icu'
        - '--icu-locale=ko'
      postInitSQL:
        - \c rms;
        - CREATE EXTENSION IF NOT EXISTS tds_fdw;
        - CREATE SERVER alis_svr FOREIGN DATA WRAPPER tds_fdw
          OPTIONS (servername '172.19.208.202', port '14032', database 'LC32_GCGENOME', msg_handler 'notice');
        - CREATE USER MAPPING FOR postgres SERVER alis_svr OPTIONS (username 'postgres', password 'postgres');