kind: ConfigMap
apiVersion: v1
metadata:
  name: rms-api-application
  namespace: {{ .Release.Namespace }}
data:
  application.yaml: |
    spring:
      application:
        name: rms-api
      config:
        import:
          - classpath:postgresql.yaml
      main:
        web-application-type: reactive
      cloud:
        kubernetes:
          config:
            sources:
              - namespace: rms-test
                name: rms-api
    aws:
      credentials:
        access-key: 8331SD7MTPDP6I16OJZT
        secret-key: mjZJcgLb8dvOlrkEWCoc9g4xEm7TZFd0otGmhqDM
      s3:
        endpoint: https://s3.apps.gcgenome.com
        bucket: bucket-86994bb8-28b7-4cbf-9842-4f314caae474
    server:
      port: 8080
