kind: ConfigMap
apiVersion: v1
metadata:
  name: rms-api-application
  namespace: {{ .Release.Namespace }}
data:
  application.yaml: |
    spring:
      application:
        name: rms-api
      main:
        web-application-type: reactive
      cloud:
        kubernetes:
          config:
            sources:
              - namespace: rms-test
                name: rms-api
        aws:
          credentials:
            access-key: 8331SD7MTPDP6I16OJZT
            secret-key: mjZJcgLb8dvOlrkEWCoc9g4xEm7TZFd0otGmhqDM
          s3:
            endpoint: https://s3.apps.gcgenome.com
            bucket: bucket-86994bb8-28b7-4cbf-9842-4f314caae474
      r2dbc:
        url: r2dbc:postgresql://rms-test-postgresql-ha-pgpool.rms-test.svc.cluster.local:5432/rms
        username: postgres
        password: snubi1004
        pool:
          initial-size: 2
          max-size: 10
          max-idle-time: 30m
          validation-query: SELECT 1
    server:
      port: 8080
