kind: Deployment
apiVersion: apps/v1
metadata:
  name: rms-api
  labels:
    app: rms-api
    app.kubernetes.io/component: rms-api
    app.kubernetes.io/instance: rms-api
    app.kubernetes.io/name: rms-api
    app.kubernetes.io/part-of: rms
    app.openshift.io/runtime: rms-api
    app.openshift.io/runtime-namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rms-api
  template:
    metadata:
      labels:
        app: rms-api
        deployment: rms-api
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      nodeSelector:
        zone: test
      volumes:
        - name: config-volume
          configMap:
            name: rms-api-application
            defaultMode: 420
      containers:
        - name: rms-api
          image: >-
            image-registry.openshift-image-registry.svc:5000/rms-test/rms-api:{{ .Chart.AppVersion }}
          ports:
            - containerPort: 8080
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: config-volume
              mountPath: /app/resources
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
