kind: Service
apiVersion: v1
metadata:
  name: rms-api
  namespace: rms-test
spec:
  type: ClusterIP
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: rms-api
    deployment: rms-api