spring:
  security:
    oauth2:
      authentication:
        header: Authorization
        jwt:
          secret: ${SECURITY_PUBLIC_KEY}
  application:
    name: rms-cart-service
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_URL}/report_service?schema=rms_dev
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    pool:
      initial-size: 2
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1
server:
  port: 9886

logging:
  level:
    io.r2dbc.postgresql.QUERY: TRACE
#    io.r2dbc.postgresql.PARAM: TRACE
