spring:
  security:
    oauth2:
      authorization:
        header: Authorization
        jwt:
          signature-algorithm: RS256
          duration: 36000
          secret: ${SECURITY_PRIVATE_KEY}
  main:
    web-application-type: reactive
  r2dbc:
    url: ${POSTGRES_R2DBC_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    pool:
      initial-size: 2
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
server:
  port: 9395