name: 프론트엔드 배포
on:
  push:
    branches:
      - feature/*
    paths:
      - rms-client/**
permissions: write-all
jobs:
  deploy:
    runs-on: ubi9
    env:
      IMAGE_REGISTRY_TEST: ${{ secrets.IMAGE_REGISTRY_TEST }}
      REGISTRY_USERNAME_TEST: ${{ secrets.REGISTRY_USERNAME_TEST }}
      REGISTRY_PASSWORD_TEST: ${{ secrets.REGISTRY_PASSWORD_TEST }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Packaging and push
        run: |
          if [[ "$GITHUB_REF_NAME" == feature/* ]]; then 
           export IMAGE="rms-test/rms-client"
           export REGISTRY_USERNAME=$REGISTRY_USERNAME_TEST
           export REGISTRY_PASSWORD=$REGISTRY_PASSWORD_TEST
           export BRANCH=feature
          else 
           echo "❌ Branch condition NOT met. Current branch: $GITHUB_REF_NAME"
          fi
          cd rms-client/rms
          chmod +x build-image.sh && \
          ./build-image.sh docker \
          -i $IMAGE:latest \
          -r image-registry.apps.gcgenome.com \
          -u $REGISTRY_USERNAME \
          -p $REGISTRY_PASSWORD \
          -b $BRANCH