name: 백엔드 배포
on:
  push:
    branches:
      - develop
    paths:
      - management-service/**
      - login-service/**
      - dashboard-service/**
      - order-service/**
      - cart-service/**
      - lims-service/**
      - api/**
      - post-service/**
      - alis-api/**
      - profile-service/**
      - catalog-service/**
      - result-service/**
      - home-service/**
permissions: write-all

jobs:
  extract:
    runs-on: ubi9
    outputs:
      matrix: ${{ steps.extract-modules.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Extract module names from changed files
        id: extract-modules
        run: |
          set -e
          changed_files="$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"
          module_names=()
          for file in $changed_files; do
            module_name="${file%%/*}"
            case "$module_name" in
              management-service|login-service|dashboard-service|order-service|cart-service|lims-service|api|post-service|alis-api|catalog-service|result-service|home-service|profile-service)
                module_names+=("$module_name")
                ;;
              *)
                echo "⏭️ Skip non-module file: $file"
                ;;
            esac
          done

          if [ ${#module_names[@]} -eq 0 ]; then
            echo "✅ No module changes detected."
            echo "matrix=[]" >> $GITHUB_OUTPUT
          else
            unique_modules=($(printf '%s\n' "${module_names[@]}" | sort -u))
            echo "✅ Detected modules: ${unique_modules[*]}"
            echo "matrix=[$(printf '"%s",' "${unique_modules[@]}" | sed 's/,$//')]" >> $GITHUB_OUTPUT
          fi
  deploy:
    needs: extract
    if: ${{ fromJson(needs.extract.outputs.matrix) != '[]' }}
    runs-on: ubi9
    strategy:
      fail-fast: true
      matrix:
        SUBMODULE: ${{ fromJSON(needs.extract.outputs.matrix) }}
    env:
      ALIS_DATABASE_URL: ${{ secrets.ALIS_DATABASE_URL }}
      ALIS_DATABASE_USERNAME: ${{ secrets.ALIS_DATABASE_USERNAME }}
      ALIS_DATABASE_PASSWORD: ${{ secrets.ALIS_DATABASE_PASSWORD }}
      DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
      DATABASE_R2DBC_URL_TEST: ${{ secrets.DATABASE_R2DBC_URL_TEST }}
      DATABASE_SCHEMA_TEST: ${{ secrets.DATABASE_SCHEMA_TEST }}
      DATABASE_USERNAME_TEST: ${{ secrets.DATABASE_USERNAME_TEST }}
      DATABASE_PASSWORD_TEST: ${{ secrets.DATABASE_PASSWORD_TEST }}
      IMAGE_REGISTRY_TEST: ${{ secrets.IMAGE_REGISTRY_TEST }}
      REGISTRY_USERNAME_TEST: ${{ secrets.REGISTRY_USERNAME_TEST }}
      REGISTRY_PASSWORD_TEST: ${{ secrets.REGISTRY_PASSWORD_TEST }}
      BASE_IMAGE: eclipse-temurin:21-jre-ubi9-minimal
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SUBMODULE: ${{ matrix.SUBMODULE }}
      S3_ACCESS_KEY: ${{secrets.S3_ACCESS_KEY}}
      S3_SECRET_KEY: ${{secrets.S3_SECRET_KEY}}
      S3_ENDPOINT: ${{secrets.S3_ENDPOINT}}
      S3_BUCKET_NAME: ${{secrets.S3_BUCKET_NAME}}
      ALIS_PRIVATE_MODULUS: ${{secrets.ALIS_PRIVATE_MODULUS}}
      ALIS_PRIVATE_EXPONENT: ${{secrets.ALIS_PRIVATE_EXPONENT}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7

      - name: Deploy
        run: |
          set -e
          echo "🚀 Starting Deploy for module: $SUBMODULE"
           
          export IMAGE="rms-test/$SUBMODULE"
          export IMAGE_REGISTRY=$IMAGE_REGISTRY_TEST
          export REGISTRY_USERNAME=$REGISTRY_USERNAME_TEST
          export REGISTRY_PASSWORD=$REGISTRY_PASSWORD_TEST
          export POSTGRES_URL=$DATABASE_URL_TEST
          export POSTGRES_R2DBC_URL=$DATABASE_R2DBC_URL_TEST
          export POSTGRES_USERNAME=$DATABASE_USERNAME_TEST
          export POSTGRES_PASSWORD=$DATABASE_PASSWORD_TEST
          export POSTGRES_SCHEMA=$DATABASE_SCHEMA_TEST
          
          TAG="latest" 
          
          gradle $SUBMODULE:jib\
            -Djib.from.image=$BASE_IMAGE \
            -Djib.from.auth.username=$DOCKER_USERNAME \
            -Djib.from.auth.password=$DOCKER_PASSWORD \
            -Djib.to.image=$IMAGE_REGISTRY/$IMAGE:$TAG \
            -Djib.to.auth.username=$REGISTRY_USERNAME \
            -Djib.to.auth.password=$REGISTRY_PASSWORD \
            -Djib.allowInsecureRegistries=true \
            -Djib.sendCredentialsOverHttp=true