name: 백엔드 배포
on:
  push:
    branches:
      - master
      - deploy
    paths:
      - rms-client/**
permissions: write-all
jobs:
  deploy:
    runs-on: ubi9
    env:
      IMAGE_REGISTRY_TEST: ${{ secrets.IMAGE_REGISTRY_TEST }}
      REGISTRY_USERNAME_TEST: ${{ secrets.REGISTRY_USERNAME_TEST }}
      REGISTRY_PASSWORD_TEST: ${{ secrets.REGISTRY_PASSWORD_TEST }}
      IMAGE_REGISTRY_DEPLOY: ${{ secrets.IMAGE_REGISTRY_DEPLOY }}
      REGISTRY_USERNAME_DEPLOY: ${{ secrets.REGISTRY_USERNAME_DEPLOY }}
      REGISTRY_PASSWORD_DEPLOY: ${{ secrets.REGISTRY_PASSWORD_DEPLOY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Packaging and push
        run: |
          if [ "$GITHUB_REF_NAME" = "master" ]; then 
           export IMAGE="rms-test/rms-client"
           export REGISTRY_USERNAME=$REGISTRY_USERNAME_TEST
           export REGISTRY_PASSWORD=$REGISTRY_PASSWORD_TEST
          else 
           export IMAGE="rms/rms-client"
           export REGISTRY_USERNAME=$REGISTRY_USERNAME_DEPLOY
           export REGISTRY_PASSWORD=$REGISTRY_PASSWORD_DEPLOY
          fi
          cd rms-client/rms
          chmod +x build-image.sh && \
          ./build-image.sh docker \
          -i $IMAGE:latest \
          -r image-registry.apps.gcgenome.com \
          -u $REGISTRY_USERNAME \
          -p $REGISTRY_PASSWORD