export enum Status {
    TOTAL = "TOTAL",
    UNCONFIRMED_ORDER = "UNCONFIRMED_ORDER",
    COMPLETED_ORDER = "COMPLETED_ORDER",
    IN_PROGRESS = "IN_PROGRESS",
    TEST_FAILED = "TEST_FAILED",
    DELIVERED = "DELIVERED",
    COMPLETED = "COMPLETED",
    CART = "CART"
}
